language: rust
cache:
  cargo: true
  directories:
    - editors/code/node_modules
    - website/node_modules
rust:
  - 1.31.0
  - stable
  - beta
  - nightly
env:
  - TRAVIS_NODE_VERSION="11.1.0"

matrix:
  allow_failures:
    - rust: nightly

install:
  - cargo build --verbose # https://docs.travis-ci.com/user/languages/rust/#Dependency-Management
  - (cd editors/code && npm install)
  - (cd website && npm install)

script:
  - cargo build --verbose --all # https://docs.travis-ci.com/user/languages/rust/#Default-Build-Script
  - cargo test --verbose --all # https://docs.travis-ci.com/user/languages/rust/#Default-Build-Script
  - (cd editors/code && npm run travis)
  - (cd website && npm run build)

deploy:
  # Deploy the website to Github Pages
  # https://docs.travis-ci.com/user/deployment/pages/
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: website/build/pikelet-site
    on:
      branch: master
      rust: stable

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/54d1cf84e3e6d80f3faa
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
