[package]
name = "pikelet"
version = "0.1.0"
authors = ["Brenda Zabarauskas"]
edition = "2018"
publish = false

[dependencies]
lalrpop-util = "0.17"
pretty = "0.7"
regex = "1.3"

[build-dependencies]
lalrpop = "0.17"
